[package]
name = "azeezd-eliasfl-hugosac-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst = {version = "0.15.3", features = ["vulkan"]}
noise = "0.7.0"
rand = "0.8.5"
